install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-graph-dev
  - sudo apt-get install -y libboost-regex-dev
  - sudo apt-get install -y libz-dev
  - sudo apt-get install -y libpthread-stubs0-dev
env:
  - HOME=$PWD
language: python
compiler:
  - python3.4
script:
  - make
notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - masab.ahmad@uconn.edu
