language: python
python:
  - "3.4"
install:
  - pip install .
  - pip install -r requirements.txt
script:
  - make
notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - masab.ahmad@uconn.edu
