env:
  - HOME=$PWD
language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install python-coveralls --use-mirrors
  - pip install nose-cov --use-mirrors
  - python setup.py install
script:
  - make
notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - masab.ahmad@uconn.edu
